name: Publish NuGet Package

on:
  push:
    branches:
      - main
      - 'releases/*'

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '8.0.x'

    - name: Set up build directory
      run: mkdir -p build

    - name: Restore dependencies
      run: dotnet restore

    - name: Build
      run: dotnet build --configuration Release --no-restore

    - name: Pack
      run: dotnet pack --configuration Release --no-build --output ./nupkg

    - name: Publish to GitHub Packages
      run: dotnet nuget push ./nupkg/*.nupkg --source "https://nuget.pkg.github.com/devlab-bmcf/index.json"
      env:
        NUGET_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
