name: Publish NuGet Package

on:
  push:
    branches:
      - main
      - 'releases/*'

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '5.0.x'

    - name: Set up build directory
      run: mkdir -p build

    - name: Restore dependencies
      run: dotnet restore
      working-directory: ./build

    - name: Build
      run: dotnet build --configuration Release --no-restore
      working-directory: ./build

    - name: Pack
      run: dotnet pack --configuration Release --no-build --output ./nupkg
      working-directory: ./build

    - name: Publish to GitHub Packages
      run: dotnet nuget push ./nupkg/*.nupkg --source "github"
      env:
        NUGET_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      working-directory: ./build
